version: '3.4'

services:
  web:
    image: newsys_web_image
    networks:
      - newsys_net
    ports:
      - "80:80"
    links:
      - was:newsys
    entrypoint:
      - "nginx"
      - "-g"
      - "daemon off;"
    depends_on:
      - was
  was:
    image: newsys_app_image
    networks:
      - newsys_net
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - db:newsys_db
    entrypoint:
      - "java"
      - "-jar"
      - "-Duser.timezone=Asia/Seoul"
      - "/app.jar"
    depends_on:
      - db
  db:
    image: mysql
    networks:
      - newsys_net
    environment:
      - MYSQL_DATABASE=newsys_schema
      - MYSQL_USER=user01
      - MYSQL_PASSWORD=user01
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - /build/DB/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

networks:
  newsys_net:

  

